# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superAdmin
      POSTGRES_PASSWORD: superPassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080