version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node